<?php
/** @var \Jahvi\NewOrderNotification\Block\Datajs $block */
$arrayData = [
    'app_id'     => $block->getAppId(),
    'app_key'    => $block->getAppKey(),
    'app_secret' => $block->getAppSecret(),
];
$serializedData = $this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode($arrayData);
?>
<script type="text/x-magento-init">
    {
        "body": {
            "newOrderNotification": <?php /* @noEscape */ echo $serializedData; ?>
        }
    }
</script>